<?php

declare(strict_types=1);

namespace Boatrace\Venture\Project\Tests\Crawlers;

use Boatrace\Venture\Project\Crawlers\OddsCrawler;
use Carbon\CarbonImmutable as Carbon;
use PHPUnit\Framework\TestCase as PHPUnitTestCase;
use Symfony\Component\BrowserKit\HttpBrowser;

/**
 * @author shimomo
 */
class OddsCrawlerTest extends PHPUnitTestCase
{
    /**
     * @var \Boatrace\Venture\Project\Crawlers\OddsCrawler
     */
    protected OddsCrawler $crawler;

    /**
     * @return void
     */
    public function setUp(): void
    {
        $this->crawler = new OddsCrawler(
            new HttpBrowser
        );
    }

    /**
     * @return void
     */
    public function testCrawl(): void
    {
        $response = $this->crawler->crawl([], Carbon::parse('2017-03-31'), 24, 1);
        $this->assertSame('2017-03-31', $response['stadiums'][24]['races'][1]['date']);
        $this->assertSame(24, $response['stadiums'][24]['races'][1]['stadium_id']);
        $this->assertSame(1, $response['stadiums'][24]['races'][1]['race_number']);
        $this->assertSame(1.0, $response['stadiums'][24]['races'][1]['oddses']['win'][1]);
        $this->assertSame(25.6, $response['stadiums'][24]['races'][1]['oddses']['win'][2]);
        $this->assertSame(33.5, $response['stadiums'][24]['races'][1]['oddses']['win'][3]);
        $this->assertSame(31.1, $response['stadiums'][24]['races'][1]['oddses']['win'][4]);
        $this->assertSame(31.1, $response['stadiums'][24]['races'][1]['oddses']['win'][5]);
        $this->assertSame(218.2, $response['stadiums'][24]['races'][1]['oddses']['win'][6]);
        $this->assertSame(1.0, $response['stadiums'][24]['races'][1]['oddses']['place'][1]['lower_limit']);
        $this->assertSame(1.0, $response['stadiums'][24]['races'][1]['oddses']['place'][1]['upper_limit']);
        $this->assertSame(1.5, $response['stadiums'][24]['races'][1]['oddses']['place'][2]['lower_limit']);
        $this->assertSame(20.9, $response['stadiums'][24]['races'][1]['oddses']['place'][2]['upper_limit']);
        $this->assertSame(2.4, $response['stadiums'][24]['races'][1]['oddses']['place'][3]['lower_limit']);
        $this->assertSame(37.8, $response['stadiums'][24]['races'][1]['oddses']['place'][3]['upper_limit']);
        $this->assertSame(2.1, $response['stadiums'][24]['races'][1]['oddses']['place'][4]['lower_limit']);
        $this->assertSame(33.3, $response['stadiums'][24]['races'][1]['oddses']['place'][4]['upper_limit']);
        $this->assertSame(2.1, $response['stadiums'][24]['races'][1]['oddses']['place'][5]['lower_limit']);
        $this->assertSame(33.3, $response['stadiums'][24]['races'][1]['oddses']['place'][5]['upper_limit']);
        $this->assertSame(5.1, $response['stadiums'][24]['races'][1]['oddses']['place'][6]['lower_limit']);
        $this->assertSame(86.6, $response['stadiums'][24]['races'][1]['oddses']['place'][6]['upper_limit']);
        $this->assertSame(1.8, $response['stadiums'][24]['races'][1]['oddses']['exacta'][1][2]);
        $this->assertSame(7.7, $response['stadiums'][24]['races'][1]['oddses']['exacta'][1][3]);
        $this->assertSame(3.8, $response['stadiums'][24]['races'][1]['oddses']['exacta'][1][4]);
        $this->assertSame(6.0, $response['stadiums'][24]['races'][1]['oddses']['exacta'][1][5]);
        $this->assertSame(48.5, $response['stadiums'][24]['races'][1]['oddses']['exacta'][1][6]);
        $this->assertSame(21.1, $response['stadiums'][24]['races'][1]['oddses']['exacta'][2][1]);
        $this->assertSame(269.3, $response['stadiums'][24]['races'][1]['oddses']['exacta'][2][3]);
        $this->assertSame(95.0, $response['stadiums'][24]['races'][1]['oddses']['exacta'][2][4]);
        $this->assertSame(126.7, $response['stadiums'][24]['races'][1]['oddses']['exacta'][2][5]);
        $this->assertSame(403.9, $response['stadiums'][24]['races'][1]['oddses']['exacta'][2][6]);
        $this->assertSame(124.2, $response['stadiums'][24]['races'][1]['oddses']['exacta'][3][1]);
        $this->assertSame(380.2, $response['stadiums'][24]['races'][1]['oddses']['exacta'][3][2]);
        $this->assertSame(430.9, $response['stadiums'][24]['races'][1]['oddses']['exacta'][3][4]);
        $this->assertSame(359.0, $response['stadiums'][24]['races'][1]['oddses']['exacta'][3][5]);
        $this->assertSame(403.9, $response['stadiums'][24]['races'][1]['oddses']['exacta'][3][6]);
        $this->assertSame(47.1, $response['stadiums'][24]['races'][1]['oddses']['exacta'][4][1]);
        $this->assertSame(109.5, $response['stadiums'][24]['races'][1]['oddses']['exacta'][4][2]);
        $this->assertSame(269.3, $response['stadiums'][24]['races'][1]['oddses']['exacta'][4][3]);
        $this->assertSame(69.5, $response['stadiums'][24]['races'][1]['oddses']['exacta'][4][5]);
        $this->assertSame(359.0, $response['stadiums'][24]['races'][1]['oddses']['exacta'][4][6]);
        $this->assertSame(30.6, $response['stadiums'][24]['races'][1]['oddses']['exacta'][5][1]);
        $this->assertSame(78.8, $response['stadiums'][24]['races'][1]['oddses']['exacta'][5][2]);
        $this->assertSame(239.3, $response['stadiums'][24]['races'][1]['oddses']['exacta'][5][3]);
        $this->assertSame(75.1, $response['stadiums'][24]['races'][1]['oddses']['exacta'][5][4]);
        $this->assertSame(258.5, $response['stadiums'][24]['races'][1]['oddses']['exacta'][5][6]);
        $this->assertSame(215.4, $response['stadiums'][24]['races'][1]['oddses']['exacta'][6][1]);
        $this->assertSame(497.1, $response['stadiums'][24]['races'][1]['oddses']['exacta'][6][2]);
        $this->assertSame(1077.0, $response['stadiums'][24]['races'][1]['oddses']['exacta'][6][3]);
        $this->assertSame(923.3, $response['stadiums'][24]['races'][1]['oddses']['exacta'][6][4]);
        $this->assertSame(359.0, $response['stadiums'][24]['races'][1]['oddses']['exacta'][6][5]);
        $this->assertSame(1.5, $response['stadiums'][24]['races'][1]['oddses']['quinella'][1][2]);
        $this->assertSame(9.0, $response['stadiums'][24]['races'][1]['oddses']['quinella'][1][3]);
        $this->assertSame(3.5, $response['stadiums'][24]['races'][1]['oddses']['quinella'][1][4]);
        $this->assertSame(5.8, $response['stadiums'][24]['races'][1]['oddses']['quinella'][1][5]);
        $this->assertSame(49.8, $response['stadiums'][24]['races'][1]['oddses']['quinella'][1][6]);
        $this->assertSame(84.3, $response['stadiums'][24]['races'][1]['oddses']['quinella'][2][3]);
        $this->assertSame(52.2, $response['stadiums'][24]['races'][1]['oddses']['quinella'][2][4]);
        $this->assertSame(64.5, $response['stadiums'][24]['races'][1]['oddses']['quinella'][2][5]);
        $this->assertSame(274.1, $response['stadiums'][24]['races'][1]['oddses']['quinella'][2][6]);
        $this->assertSame(156.6, $response['stadiums'][24]['races'][1]['oddses']['quinella'][3][4]);
        $this->assertSame(156.6, $response['stadiums'][24]['races'][1]['oddses']['quinella'][3][5]);
        $this->assertSame(274.1, $response['stadiums'][24]['races'][1]['oddses']['quinella'][3][6]);
        $this->assertSame(52.2, $response['stadiums'][24]['races'][1]['oddses']['quinella'][4][5]);
        $this->assertSame(274.1, $response['stadiums'][24]['races'][1]['oddses']['quinella'][4][6]);
        $this->assertSame(109.6, $response['stadiums'][24]['races'][1]['oddses']['quinella'][5][6]);
        $this->assertSame(1.0, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][2]['lower_limit']);
        $this->assertSame(1.2, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][2]['upper_limit']);
        $this->assertSame(1.8, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][3]['lower_limit']);
        $this->assertSame(2.5, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][3]['upper_limit']);
        $this->assertSame(1.6, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][4]['lower_limit']);
        $this->assertSame(2.5, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][4]['upper_limit']);
        $this->assertSame(2.4, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][5]['lower_limit']);
        $this->assertSame(3.6, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][5]['upper_limit']);
        $this->assertSame(7.9, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][6]['lower_limit']);
        $this->assertSame(10.9, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][1][6]['upper_limit']);
        $this->assertSame(2.9, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][2][3]['lower_limit']);
        $this->assertSame(4.8, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][2][3]['upper_limit']);
        $this->assertSame(2.0, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][2][4]['lower_limit']);
        $this->assertSame(3.3, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][2][4]['upper_limit']);
        $this->assertSame(2.8, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][2][5]['lower_limit']);
        $this->assertSame(4.4, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][2][5]['upper_limit']);
        $this->assertSame(12.5, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][2][6]['lower_limit']);
        $this->assertSame(18.0, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][2][6]['upper_limit']);
        $this->assertSame(11.7, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][3][4]['lower_limit']);
        $this->assertSame(15.0, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][3][4]['upper_limit']);
        $this->assertSame(8.8, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][3][5]['lower_limit']);
        $this->assertSame(10.6, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][3][5]['upper_limit']);
        $this->assertSame(44.9, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][3][6]['lower_limit']);
        $this->assertSame(50.7, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][3][6]['upper_limit']);
        $this->assertSame(5.0, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][4][5]['lower_limit']);
        $this->assertSame(6.1, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][4][5]['upper_limit']);
        $this->assertSame(25.7, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][4][6]['lower_limit']);
        $this->assertSame(29.3, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][4][6]['upper_limit']);
        $this->assertSame(23.7, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][5][6]['lower_limit']);
        $this->assertSame(25.5, $response['stadiums'][24]['races'][1]['oddses']['quinella_place'][5][6]['upper_limit']);
        $this->assertSame(9.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][2][3]);
        $this->assertSame(3.6, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][2][4]);
        $this->assertSame(4.6, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][2][5]);
        $this->assertSame(57.7, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][2][6]);
        $this->assertSame(23.5, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][3][2]);
        $this->assertSame(26.1, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][3][4]);
        $this->assertSame(31.2, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][3][5]);
        $this->assertSame(147.3, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][3][6]);
        $this->assertSame(8.9, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][4][2]);
        $this->assertSame(29.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][4][3]);
        $this->assertSame(13.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][4][5]);
        $this->assertSame(75.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][4][6]);
        $this->assertSame(14.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][5][2]);
        $this->assertSame(34.9, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][5][3]);
        $this->assertSame(20.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][5][4]);
        $this->assertSame(85.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][5][6]);
        $this->assertSame(196.3, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][6][2]);
        $this->assertSame(346.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][6][3]);
        $this->assertSame(209.9, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][6][4]);
        $this->assertSame(221.7, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][1][6][5]);
        $this->assertSame(91.6, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][1][3]);
        $this->assertSame(62.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][1][4]);
        $this->assertSame(63.2, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][1][5]);
        $this->assertSame(228.1, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][1][6]);
        $this->assertSame(513.3, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][3][1]);
        $this->assertSame(870.1, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][3][4]);
        $this->assertSame(814.9, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][3][5]);
        $this->assertSame(1555.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][3][6]);
        $this->assertSame(209.1, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][4][1]);
        $this->assertSame(862.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][4][3]);
        $this->assertSame(338.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][4][5]);
        $this->assertSame(1267.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][4][6]);
        $this->assertSame(198.2, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][5][1]);
        $this->assertSame(828.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][5][3]);
        $this->assertSame(390.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][5][4]);
        $this->assertSame(968.6, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][5][6]);
        $this->assertSame(1555.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][6][1]);
        $this->assertSame(2139.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][6][3]);
        $this->assertSame(2387.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][6][4]);
        $this->assertSame(1974.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][2][6][5]);
        $this->assertSame(390.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][1][2]);
        $this->assertSame(518.5, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][1][4]);
        $this->assertSame(448.3, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][1][5]);
        $this->assertSame(1166.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][1][6]);
        $this->assertSame(772.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][2][1]);
        $this->assertSame(1333.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][2][4]);
        $this->assertSame(1509.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][2][5]);
        $this->assertSame(2775.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][2][6]);
        $this->assertSame(933.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][4][1]);
        $this->assertSame(1299.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][4][2]);
        $this->assertSame(1351.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][4][5]);
        $this->assertSame(2184.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][4][6]);
        $this->assertSame(908.6, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][5][1]);
        $this->assertSame(1740.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][5][2]);
        $this->assertSame(1866.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][5][4]);
        $this->assertSame(2013.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][5][6]);
        $this->assertSame(2852.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][6][1]);
        $this->assertSame(2933.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][6][2]);
        $this->assertSame(1937.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][6][4]);
        $this->assertSame(2184.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][3][6][5]);
        $this->assertSame(120.9, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][1][2]);
        $this->assertSame(397.9, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][1][3]);
        $this->assertSame(133.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][1][5]);
        $this->assertSame(561.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][1][6]);
        $this->assertSame(220.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][2][1]);
        $this->assertSame(987.2, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][2][3]);
        $this->assertSame(386.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][2][5]);
        $this->assertSame(1466.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][2][6]);
        $this->assertSame(870.1, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][3][1]);
        $this->assertSame(1047.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][3][2]);
        $this->assertSame(1180.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][3][5]);
        $this->assertSame(1711.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][3][6]);
        $this->assertSame(196.7, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][5][1]);
        $this->assertSame(365.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][5][2]);
        $this->assertSame(942.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][5][3]);
        $this->assertSame(744.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][5][6]);
        $this->assertSame(1047.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][6][1]);
        $this->assertSame(1237.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][6][2]);
        $this->assertSame(1833.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][6][3]);
        $this->assertSame(1426.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][4][6][5]);
        $this->assertSame(109.9, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][1][2]);
        $this->assertSame(284.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][1][3]);
        $this->assertSame(158.9, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][1][4]);
        $this->assertSame(338.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][1][6]);
        $this->assertSame(194.8, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][2][1]);
        $this->assertSame(855.6, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][2][3]);
        $this->assertSame(431.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][2][4]);
        $this->assertSame(987.2, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][2][6]);
        $this->assertSame(603.9, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][3][1]);
        $this->assertSame(1222.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][3][2]);
        $this->assertSame(1237.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][3][4]);
        $this->assertSame(1466.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][3][6]);
        $this->assertSame(247.4, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][4][1]);
        $this->assertSame(482.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][4][2]);
        $this->assertSame(1006.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][4][3]);
        $this->assertSame(1037.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][4][6]);
        $this->assertSame(693.7, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][6][1]);
        $this->assertSame(1193.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][6][2]);
        $this->assertSame(1267.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][6][3]);
        $this->assertSame(1092.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][5][6][4]);
        $this->assertSame(1406.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][1][2]);
        $this->assertSame(2095.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][1][3]);
        $this->assertSame(1509.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][1][4]);
        $this->assertSame(1252.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][1][5]);
        $this->assertSame(2095.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][2][1]);
        $this->assertSame(3540.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][2][3]);
        $this->assertSame(2933.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][2][4]);
        $this->assertSame(2387.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][2][5]);
        $this->assertSame(3312.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][3][1]);
        $this->assertSame(4107.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][3][2]);
        $this->assertSame(2444.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][3][4]);
        $this->assertSame(3422.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][3][5]);
        $this->assertSame(2013.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][4][1]);
        $this->assertSame(2702.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][4][2]);
        $this->assertSame(2333.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][4][3]);
        $this->assertSame(2504.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][4][5]);
        $this->assertSame(1351.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][5][1]);
        $this->assertSame(2852.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][5][2]);
        $this->assertSame(2852.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][5][3]);
        $this->assertSame(2632.0, $response['stadiums'][24]['races'][1]['oddses']['trifecta'][6][5][4]);
        $this->assertSame(6.5, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][2][3]);
        $this->assertSame(2.4, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][2][4]);
        $this->assertSame(3.2, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][2][5]);
        $this->assertSame(27.2, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][2][6]);
        $this->assertSame(13.3, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][3][4]);
        $this->assertSame(13.4, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][3][5]);
        $this->assertSame(77.7, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][3][6]);
        $this->assertSame(7.1, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][4][5]);
        $this->assertSame(37.5, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][4][6]);
        $this->assertSame(48.3, $response['stadiums'][24]['races'][1]['oddses']['trio'][1][5][6]);
        $this->assertSame(114.5, $response['stadiums'][24]['races'][1]['oddses']['trio'][2][3][4]);
        $this->assertSame(94.6, $response['stadiums'][24]['races'][1]['oddses']['trio'][2][3][5]);
        $this->assertSame(241.9, $response['stadiums'][24]['races'][1]['oddses']['trio'][2][3][6]);
        $this->assertSame(34.5, $response['stadiums'][24]['races'][1]['oddses']['trio'][2][4][5]);
        $this->assertSame(120.9, $response['stadiums'][24]['races'][1]['oddses']['trio'][2][4][6]);
        $this->assertSame(311.0, $response['stadiums'][24]['races'][1]['oddses']['trio'][2][5][6]);
        $this->assertSame(136.0, $response['stadiums'][24]['races'][1]['oddses']['trio'][3][4][5]);
        $this->assertSame(155.5, $response['stadiums'][24]['races'][1]['oddses']['trio'][3][4][6]);
        $this->assertSame(197.9, $response['stadiums'][24]['races'][1]['oddses']['trio'][3][5][6]);
        $this->assertSame(167.4, $response['stadiums'][24]['races'][1]['oddses']['trio'][4][5][6]);
    }

    /**
     * @return void
     */
    public function testCrawlInCaseOfCancellation(): void
    {
        $response = $this->crawler->crawl([], Carbon::parse('2019-10-14'), 2, 1);
        $this->assertSame('2019-10-14', $response['stadiums'][2]['races'][1]['date']);
        $this->assertSame(2, $response['stadiums'][2]['races'][1]['stadium_id']);
        $this->assertSame(1, $response['stadiums'][2]['races'][1]['race_number']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['win'][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['win'][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['win'][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['win'][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['win'][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['win'][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][1]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][1]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][2]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][2]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][3]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][3]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][4]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][4]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][5]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][5]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][6]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['place'][6]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][1][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][1][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][1][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][1][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][1][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][2][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][2][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][2][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][2][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][2][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][3][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][3][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][3][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][3][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][3][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][4][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][4][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][4][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][4][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][4][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][5][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][5][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][5][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][5][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][5][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][6][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][6][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][6][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][6][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['exacta'][6][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][1][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][1][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][1][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][1][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][1][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][2][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][2][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][2][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][2][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][3][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][3][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][3][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][4][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][4][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella'][5][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][2]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][2]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][3]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][3]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][4]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][4]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][5]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][5]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][6]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][1][6]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][2][3]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][2][3]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][2][4]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][2][4]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][2][5]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][2][5]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][2][6]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][2][6]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][3][4]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][3][4]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][3][5]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][3][5]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][3][6]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][3][6]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][4][5]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][4][5]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][4][6]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][4][6]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][5][6]['lower_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['quinella_place'][5][6]['upper_limit']);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][2][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][2][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][2][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][2][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][3][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][3][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][3][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][3][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][4][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][4][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][4][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][4][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][5][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][5][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][5][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][5][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][6][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][6][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][6][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][1][6][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][1][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][1][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][1][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][1][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][3][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][3][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][3][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][3][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][4][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][4][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][4][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][4][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][5][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][5][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][5][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][5][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][6][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][6][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][6][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][2][6][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][1][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][1][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][1][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][1][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][2][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][2][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][2][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][2][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][4][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][4][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][4][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][4][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][5][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][5][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][5][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][5][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][6][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][6][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][6][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][3][6][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][1][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][1][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][1][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][1][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][2][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][2][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][2][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][2][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][3][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][3][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][3][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][3][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][5][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][5][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][5][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][5][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][6][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][6][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][6][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][4][6][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][1][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][1][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][1][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][1][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][2][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][2][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][2][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][2][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][3][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][3][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][3][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][3][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][4][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][4][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][4][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][4][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][6][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][6][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][6][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][5][6][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][1][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][1][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][1][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][1][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][2][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][2][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][2][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][2][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][3][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][3][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][3][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][3][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][4][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][4][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][4][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][4][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][5][1]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][5][2]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][5][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trifecta'][6][5][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][2][3]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][2][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][2][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][2][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][3][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][3][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][3][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][4][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][4][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][1][5][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][2][3][4]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][2][3][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][2][3][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][2][4][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][2][4][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][2][5][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][3][4][5]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][3][4][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][3][5][6]);
        $this->assertNull($response['stadiums'][2]['races'][1]['oddses']['trio'][4][5][6]);
    }
}
